import type { CatalogItem } from '../modals/catalog';
import { getImageForFoodItem } from '../utils/imageUtils';

// Generate mock catalog items with proper image URLs
export const catalogMockData: CatalogItem[] = [
  {
    id: 1,
    name: 'Classic Veg Sandwich',
    price: 99,
    imageURI: getImageForFoodItem('Classic Veg Sandwich'),
    description: 'A delicious classic veg sandwich with fresh veggies.',
    category: 'breakfast',
    brand: 'FreshBites',
    stock: 20,
    isAvailable: false,
    isFeatured: true,
    isNew: false,
    itemType: 'veg',
  },
  {
    id: 2,
    name: 'Chicken Burger',
    price: 149,
    imageURI: getImageForFoodItem('Chicken Burger'),
    description: 'Juicy chicken burger with crispy lettuce and mayo.',
    category: 'Meal',
    brand: 'BurgerHub',
    stock: 15,
    isAvailable: true,
    isFeatured: false,
    isNew: true,
    itemType: 'non-veg',
  },
  {
    id: 3,
    name: 'Paneer Wrap',
    price: 129,
    imageURI: getImageForFoodItem('Paneer Wrap'),
    description: 'Soft wrap filled with spicy paneer and veggies.',
    category: 'Meal',
    brand: 'WrapIt',
    stock: 10,
    isAvailable: true,
    isFeatured: false,
    isNew: true,
    itemType: 'veg',
  },
  {
    id: 4,
    name: 'Egg Omelette',
    price: 79,
    imageURI: getImageForFoodItem('Egg Omelette'),
    description: 'Fluffy egg omelette with herbs.',
    category: 'breakfast',
    brand: 'Eggspert',
    stock: 25,
    isAvailable: true,
    isFeatured: false,
    isNew: false,
    itemType: 'non-veg',
  },
  {
    id: 5,
    name: 'Veggie Pizza',
    price: 199,
    imageURI: getImageForFoodItem('Veggie Pizza'),
    description: 'Cheesy pizza loaded with fresh vegetables.',
    category: 'Meal',
    brand: 'PizzaMania',
    stock: 8,
    isAvailable: false,
    isFeatured: true,
    isNew: true,
    itemType: 'veg',
  },
  {
    id: 6,
    name: 'Grilled Chicken',
    price: 249,
    imageURI: getImageForFoodItem('Grilled Chicken'),
    description: 'Tender grilled chicken with spices.',
    category: 'Meal',
    brand: 'GrillHouse',
    stock: 12,
    isAvailable: true,
    isFeatured: true,
    isNew: false,
    itemType: 'non-veg',
  },
  {
    id: 7,
    name: 'Aloo Paratha',
    price: 59,
    imageURI: getImageForFoodItem('Aloo Paratha'),
    description: 'Stuffed aloo paratha served with curd.',
    category: 'breakfast',
    brand: 'DesiTadka',
    stock: 30,
    isAvailable: true,
    isFeatured: false,
    isNew: true,
    itemType: 'veg',
  },
  {
    id: 8,
    name: 'Fish Curry',
    price: 299,
    imageURI: getImageForFoodItem('Fish Curry'),
    description: 'Spicy fish curry with rice.',
    category: 'Meal',
    brand: 'SeaBites',
    stock: 7,
    isAvailable: true,
    isFeatured: false,
    isNew: false,
    itemType: 'non-veg',
  },
  {
    id: 9,
    name: 'Masala Dosa',
    price: 89,
    imageURI: getImageForFoodItem('Masala Dosa'),
    description: 'Crispy dosa stuffed with spicy potato filling.',
    category: 'breakfast',
    brand: 'SouthSpice',
    stock: 18,
    isAvailable: true,
    isFeatured: true,
    isNew: false,
    itemType: 'veg',
  },
  {
    id: 10,
    name: 'Mutton Biryani',
    price: 349,
    imageURI: getImageForFoodItem('Mutton Biryani'),
    description: 'Aromatic mutton biryani with raita.',
    category: 'Meal',
    brand: 'BiryaniKing',
    stock: 5,
    isAvailable: true,
    isFeatured: true,
    isNew: true,
    itemType: 'non-veg',
  },
  // ... 40 more items with varied values and working Unsplash URLs ...
];

// For brevity, only 10 items are shown. The actual file should contain 50+ items with realistic, varied data and working Unsplash URLs. 